# Generated by Django 4.1.7 on 2023-06-29 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('description', models.TextField(db_column='description', max_length=256)),
                ('location', models.CharField(db_column='location', max_length=256)),
                ('address', models.CharField(db_column='address', max_length=256)),
                ('approval_status', models.BooleanField()),
                ('phone_number', models.CharField(db_column='phone_number', max_length=20)),
            ],
            options={
                'db_table': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=256)),
                ('last_name', models.CharField(db_column='last_name', max_length=256)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=256)),
                ('email_address', models.EmailField(db_column='email_address', max_length=256, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('request_creation', models.DateTimeField(auto_now_add=True)),
                ('user_comment', models.CharField(max_length=256)),
                ('party_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_smoking', models.BooleanField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('table_id', models.SmallIntegerField(blank=True, null=True)),
                ('restaurant_id', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='RB_APP.restaurant')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='RB_APP.user')),
            ],
            options={
                'db_table': 'Reservations',
            },
        ),
    ]
