# Generated by Django 4.1.7 on 2023-07-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0004_userdetails_restaurant_restaurant_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='DetailedUser',
        ),
    ]
