# Generated by Django 4.1.7 on 2023-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0005_alter_userdetails_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
