# Generated by Django 4.1.7 on 2023-07-16 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0008_alter_reservation_user_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_inside', models.BooleanField(blank=True, null=True)),
                ('smoker', models.BooleanField(blank=True, null=True)),
                ('bar', models.BooleanField(blank=True, null=True)),
                ('near_window', models.BooleanField(blank=True, null=True)),
                ('restaurant_id', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.RESTRICT, to='RB_APP.restaurant')),
            ],
            options={
                'db_table': 'Table',
            },
        ),
    ]
