# Generated by Django 4.1.7 on 2023-07-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0009_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['user_id']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['id']},
        ),
    ]
