# Generated by Django 4.1.7 on 2023-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0010_alter_reservation_options_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
