# Generated by Django 4.1.7 on 2023-07-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0011_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_owner',
            field=models.ManyToManyField(related_name='rest_owners', to='RB_APP.userdetails'),
        ),
    ]
