# Generated by Django 4.1.7 on 2023-07-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0012_restaurant_is_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='is_owner',
            new_name='owners',
        ),
    ]
