# Generated by Django 4.1.7 on 2023-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0014_alter_restaurant_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owners',
            field=models.ManyToManyField(related_name='restaurants_owned', to='RB_APP.userdetails'),
        ),
    ]
