# Generated by Django 4.1.7 on 2023-08-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0017_alter_restaurant_description_alter_restaurant_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_picture',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
