# Generated by Django 4.1.7 on 2023-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0019_remove_restaurant_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_picture',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
