# Generated by Django 4.1.7 on 2023-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0020_restaurant_logo_restaurant_rest_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
