# Generated by Django 4.1.7 on 2023-08-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0021_reservation_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='outside',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
