# Generated by Django 4.1.7 on 2023-09-01 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0023_restauranttype_alter_restaurant_owners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='RB_APP.table'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurants',
            field=models.ManyToManyField(blank=True, null=True, related_name='cuisines_list', to='RB_APP.cuisine'),
        ),
        migrations.AlterField(
            model_name='restauranttype',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
