# Generated by Django 4.1.7 on 2023-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0024_remove_cuisine_restaurants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_types',
            field=models.ManyToManyField(blank=True, related_name='type_restaurants', to='RB_APP.restauranttype'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='cuisines_list', to='RB_APP.cuisine'),
        ),
    ]
