# Generated by Django 4.1.7 on 2023-09-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0025_alter_restaurant_rest_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurants',
            new_name='cuisine_type',
        ),
    ]
