# Generated by Django 4.1.7 on 2023-09-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0026_rename_restaurants_restaurant_cuisine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(choices=[('איטלקי', 'Italian'), ('מקסיקני', 'Mexican'), ('סיני', 'Chinese'), ('יפני', 'Japanese'), ('הודי', 'Indian'), ('צרפתי', 'French'), ('תאילנדי', 'Thai'), ('תיכוני', 'Mediterranean'), ('קוריאני', 'Korean'), ('אמריקאי', 'American'), ('יווני', 'Greek'), ('ספרדי', 'Spanish'), ('ויאטנמי', 'Vietnamese'), ('מזרח תיכוני', 'Middle Eastern'), ('ברזילאי', 'Brazilian'), ('ארגנטינאי', 'Argentinian')], max_length=100),
        ),
    ]
