# Generated by Django 4.1.7 on 2023-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RB_APP', '0027_alter_cuisine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttype',
            name='type',
            field=models.CharField(choices=[('מסעדה', 'Restaurant'), ('בר', 'Bar'), ('יקב', 'Winery'), ('שף פרטי', 'Chef')], max_length=100),
        ),
    ]
